import type { Metadata } from 'next'
import { Onest } from 'next/font/google'
import '@/styles/global.css'
import NavBar from '@/components/navigation/Navbar'
import { NavMenuDrawerStoreProvider } from '@/providers/customer/nav-menu-drawer-store-provider'
import { UserStoreProvider } from '@/providers/user/user-store-provider'
import AuthWrapper from '@/components/auth/auth-wrapper'
import { Toast } from '@itsallsavvy/savvy-resuable-components'
import FaIcon from '@/components/common/fa-icon'
import { faCircleCheck, faCircleXmark } from '@fortawesome/free-solid-svg-icons'
import { SWRConfig } from 'swr'
import {
   ShopConfigStoreContext,
   ShopConfigStoreProvider,
} from '@/providers/global/shop-config-store-provider'
import { Providers } from '@/providers/providers'

const onest = Onest({ subsets: ['latin'] })

export const metadata: Metadata = {
   title: 'Savvy',
   description: 'Generated by create next app',
}

export default async function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en">
         <body className={onest.className}>
            <Providers navbar={<NavBar />}>{children}</Providers>
         </body>
      </html>
   )
}
