# name: Deploy

# on:
#    push:
#       branches:
#          - main

# jobs:
#    deploy:
#       runs-on: ubuntu-latest

#       steps:
#          - name: Checkout code
#            uses: actions/checkout@v3

#          - name: Setup Node.js
#            uses: actions/setup-node@v3
#            with:
#               node-version: '18'

#          - name: Deploy
#            env:
#               AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#               AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#            run: |
#               npm i && npx sst deploy --stage savvy
